---
env:
  global:
    - CC_TEST_REPORTER_ID=af2e8c9926358c9cdd7b6126a6cf44852adbeb68ff5c2f8f774b33a26b59861e
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn lint
  - yarn test:coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
